Update pre-commit status to raise have exit code

diff --git a/.github/workflows/cancel_on_status.yml b/.github/workflows/cancel_on_status.yml
--- a/.github/workflows/cancel_on_status.yml
+++ b/.github/workflows/cancel_on_status.yml
@@ -16,17 +16,19 @@ on:
 concurrency:
   group: ${{ github.ref }}
   cancel-in-progress: true
+
 jobs:
 
   if_error_or_failure:
     runs-on: ubuntu-latest
     steps:
-      - name: Sleep for 30 seconds
+      - name: Sleep for 60 seconds
         shell: bash -l {0}
         run: sleep 60s
       - env:
           DESCRIPTION: ${{ github.event.description }}
           STATUS: ${{ github.event.state }}
         run: |
-          echo The status is error or failed: $DESCRIPTION
-          echo $STATUS
+          echo The event description is: $DESCRIPTION
+          echo The status is: $STATUS
+          if [[ $STATUS == 'error' || $STATUS == 'failure' ]]; then exit 0; else exit 1;
