Update cancel_on_status.yml

diff --git a/.github/workflows/cancel_on_status.yml b/.github/workflows/cancel_on_status.yml
--- a/.github/workflows/cancel_on_status.yml
+++ b/.github/workflows/cancel_on_status.yml
@@ -16,3 +16,4 @@ jobs:
         run: |
           echo The status is error or failed: $DESCRIPTION
           echo $STATUS
+          if [[ $STATUS == 'error' || $STATUS == 'failure' ]]; then exit 1; else exit 0; fi
