Integrate pre-commit.ci check into testing workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,7 +33,7 @@ jobs:
         run: |
           echo The event description is: $DESCRIPTION
           echo The status is: $STATUS
-          if [[ $STATUS == 'error' || $STATUS == 'failure' ]]; then exit 0; else exit 1;
+          if [[ $STATUS == 'error' || $STATUS == 'failure' ]]; then exit 1; else exit 0; fi
 
   miniconda:
     name: Miniconda ${{ matrix.os }}-${{ matrix.python-version }}
